import { Vehicle, Alert, EntryExitLog, CameraConfig, AnalyticsData, Detection } from '../types';

export const INITIAL_CAMERAS: CameraConfig[] = [
  {
    id: 'Gate-01',
    name: 'Gate 01 - North Heavy Haul',
    location: 'North Ingress / Concrete & Aggregate Delivery',
    rtsp_url: 'rtsp://cctv.site.internal/stream/gate1',
    fps: 30,
    status: 'online',
    entry_line_y: 0.38,
    exit_line_y: 0.72,
  },
  {
    id: 'Gate-02',
    name: 'Gate 02 - South Materials Gate',
    location: 'South Access / Structural Steel & Rebar',
    rtsp_url: 'rtsp://cctv.site.internal/stream/gate2',
    fps: 25,
    status: 'online',
    entry_line_y: 0.42,
    exit_line_y: 0.76,
  },
  {
    id: 'Gate-03',
    name: 'Gate 03 - Contractor & Logistics',
    location: 'East Gate / Subcontractor & Inspection Vehicles',
    rtsp_url: 'rtsp://cctv.site.internal/stream/gate3',
    fps: 30,
    status: 'online',
    entry_line_y: 0.35,
    exit_line_y: 0.68,
  },
];

export const INITIAL_VEHICLES: Vehicle[] = [
  {
    id: 'veh-pb01m0060',
    vehicle_id: 'REG-100',
    plate_number: 'PB01M0060',
    vehicle_type: 'Car',
    company: 'Site Engineering & Quality Inspection',
    driver_name: 'Project Engineer',
    contact_number: '+91 98765 43210',
    authorization_status: 'authorized',
    permit_start_date: '2026-01-01',
    permit_expiry_date: '2026-12-31',
    notes: 'Official project inspection vehicle. Priority gate clearance approved.',
    created_at: '2026-01-05T08:00:00Z',
  },
  {
    id: 'veh-001',
    vehicle_id: 'REG-101',
    plate_number: 'TN38AB1234',
    vehicle_type: 'Truck',
    company: 'ABC Construction Ltd',
    driver_name: 'Murugan Selvam',
    contact_number: '+91 98452 11029',
    authorization_status: 'authorized',
    permit_start_date: '2026-01-01',
    permit_expiry_date: '2026-12-31',
    notes: 'Approved for heavy earth-moving equipment transport.',
    created_at: '2026-01-10T08:00:00Z',
  },
  {
    id: 'veh-002',
    vehicle_id: 'REG-102',
    plate_number: 'KA04MH5678',
    vehicle_type: 'Concrete Mixer',
    company: 'Apex Ready-Mix Concrete',
    driver_name: 'Rajesh Kumar',
    contact_number: '+91 94481 29384',
    authorization_status: 'authorized',
    permit_start_date: '2026-02-15',
    permit_expiry_date: '2026-10-30',
    notes: 'Daily concrete supply pour permit. Gate 1 priority.',
    created_at: '2026-02-15T09:30:00Z',
  },
  {
    id: 'veh-003',
    vehicle_id: 'REG-103',
    plate_number: 'MH12PQ9988',
    vehicle_type: 'Dump Truck',
    company: 'Titan Earthworks & Quarry',
    driver_name: 'Vikram Shinde',
    contact_number: '+91 97632 44510',
    authorization_status: 'authorized',
    permit_start_date: '2026-03-01',
    permit_expiry_date: '2026-11-15',
    notes: 'Excavation debris disposal fleet.',
    created_at: '2026-03-01T07:15:00Z',
  },
  {
    id: 'veh-004',
    vehicle_id: 'REG-104',
    plate_number: 'DL01CA4321',
    vehicle_type: 'Flatbed',
    company: 'SteelCraft Infrastructure',
    driver_name: 'Gurpreet Singh',
    contact_number: '+91 98110 87342',
    authorization_status: 'authorized',
    permit_start_date: '2026-04-01',
    permit_expiry_date: '2026-09-30',
    notes: 'Structural steel girder deliveries.',
    created_at: '2026-04-01T11:00:00Z',
  },
  {
    id: 'veh-005',
    vehicle_id: 'REG-105',
    plate_number: 'TN40XX9999',
    vehicle_type: 'Lorry',
    company: 'Unknown / Unregistered Hauler',
    driver_name: 'Unregistered Driver',
    contact_number: 'N/A',
    authorization_status: 'unauthorized',
    permit_start_date: '2025-01-01',
    permit_expiry_date: '2025-06-01',
    notes: 'Repeated unauthorized access attempts flagged by security.',
    created_at: '2026-05-12T14:20:00Z',
  },
  {
    id: 'veh-006',
    vehicle_id: 'REG-106',
    plate_number: 'KA51MD3344',
    vehicle_type: 'Van',
    company: 'ElectroSpark MEP Services',
    driver_name: 'Anand Rao',
    contact_number: '+91 99002 54189',
    authorization_status: 'expired',
    permit_start_date: '2026-01-01',
    permit_expiry_date: '2026-08-31',
    notes: 'Subcontractor electrical crew permit expired on Aug 31, 2026.',
    created_at: '2026-01-05T10:00:00Z',
  },
  {
    id: 'veh-007',
    vehicle_id: 'REG-107',
    plate_number: 'KL07CE7711',
    vehicle_type: 'Pickup',
    company: 'Skyline Site Surveying',
    driver_name: 'Mathews George',
    contact_number: '+91 94950 12893',
    authorization_status: 'authorized',
    permit_start_date: '2026-05-01',
    permit_expiry_date: '2026-12-15',
    notes: 'Site survey team utility vehicle.',
    created_at: '2026-05-01T08:45:00Z',
  },
  {
    id: 'veh-008',
    vehicle_id: 'REG-108',
    plate_number: 'TS09UB4567',
    vehicle_type: 'Truck',
    company: 'Precision Cranes & Rigging',
    driver_name: 'Syed Rahmath',
    contact_number: '+91 98480 33219',
    authorization_status: 'authorized',
    permit_start_date: '2026-02-01',
    permit_expiry_date: '2026-11-30',
    notes: 'Mobile counterweight delivery truck.',
    created_at: '2026-02-01T13:10:00Z',
  },
  {
    id: 'veh-009',
    vehicle_id: 'REG-109',
    plate_number: 'TN22BZ8890',
    vehicle_type: 'Concrete Mixer',
    company: 'ABC Construction Ltd',
    driver_name: 'K. Balaji',
    contact_number: '+91 97910 65432',
    authorization_status: 'authorized',
    permit_start_date: '2026-01-15',
    permit_expiry_date: '2026-12-31',
    notes: 'Fleet mixer #04.',
    created_at: '2026-01-15T09:00:00Z',
  },
  {
    id: 'veh-010',
    vehicle_id: 'REG-110',
    plate_number: 'HR26DK5566',
    vehicle_type: 'Dump Truck',
    company: 'National Aggregate Supply',
    driver_name: 'Kuldeep Yadav',
    contact_number: '+91 98104 99012',
    authorization_status: 'expired',
    permit_start_date: '2026-03-01',
    permit_expiry_date: '2026-09-01',
    notes: 'Aggregate supplier permit expired 2 weeks ago.',
    created_at: '2026-03-01T10:30:00Z',
  }
];

export const INITIAL_ALERTS: Alert[] = [
  {
    id: 'alt-001',
    type: 'unauthorized_vehicle',
    title: 'Unauthorized Vehicle Detected',
    description: 'Vehicle plate TN40XX9999 has no registered entry permit or contractor affiliation.',
    plate_number: 'TN40XX9999',
    vehicle_id: 'V048',
    camera_id: 'Gate-01',
    camera_name: 'Gate 01 - North Heavy Haul',
    timestamp: '2026-09-17 11:24 AM',
    status: 'new',
    severity: 'high',
  },
  {
    id: 'alt-002',
    type: 'expired_permit',
    title: 'Expired Site Permit Ingress',
    description: 'Permit for contractor vehicle KA51MD3344 (ElectroSpark MEP) expired on 2026-08-31.',
    plate_number: 'KA51MD3344',
    vehicle_id: 'V039',
    camera_id: 'Gate-03',
    camera_name: 'Gate 03 - Contractor & Logistics',
    timestamp: '2026-09-17 10:15 AM',
    status: 'new',
    severity: 'medium',
  },
  {
    id: 'alt-003',
    type: 'low_confidence_ocr',
    title: 'Low-Confidence OCR Warning',
    description: 'Plate obscured by construction mud/slurry. Quality score: 34%. OCR confidence: 58%.',
    plate_number: 'TN38??7812',
    vehicle_id: 'V031',
    camera_id: 'Gate-01',
    camera_name: 'Gate 01 - North Heavy Haul',
    timestamp: '2026-09-17 09:42 AM',
    status: 'reviewed',
    severity: 'low',
    assigned_to: 'Security Guard Gate 1',
    resolution_notes: 'Driver manually cleared dust; security verified plate physically.',
  },
  {
    id: 'alt-004',
    type: 'unauthorized_vehicle',
    title: 'Unauthorized Delivery Attempt',
    description: 'Unregistered flatbed attempted ingress at South Gate without manifest paperwork.',
    plate_number: 'GJ01XY4455',
    vehicle_id: 'V022',
    camera_id: 'Gate-02',
    camera_name: 'Gate 02 - South Materials Gate',
    timestamp: '2026-09-17 08:30 AM',
    status: 'resolved',
    severity: 'high',
    assigned_to: 'Site Security Chief',
    resolution_notes: 'Turned away at gate by security officer.',
  },
  {
    id: 'alt-005',
    type: 'unreadable_plate',
    title: 'Unreadable License Plate',
    description: 'Heavy blur and sunlight glare prevented license plate character extraction.',
    plate_number: 'UNREADABLE',
    vehicle_id: 'V019',
    camera_id: 'Gate-02',
    camera_name: 'Gate 02 - South Materials Gate',
    timestamp: '2026-09-17 07:55 AM',
    status: 'reviewed',
    severity: 'medium',
  }
];

export const INITIAL_HISTORY: EntryExitLog[] = [
  {
    id: 'log-001',
    vehicle_id: 'V023',
    plate_number: 'TN38AB1234',
    vehicle_type: 'Truck',
    company: 'ABC Construction Ltd',
    driver_name: 'Murugan Selvam',
    camera_id: 'Gate-01',
    entry_time: '09:12 AM',
    exit_time: '10:47 AM',
    duration_minutes: 95,
    authorization_status: 'authorized',
    status: 'Exited',
    date: '2026-09-17',
    ocr_confidence: 97,
  },
  {
    id: 'log-002',
    vehicle_id: 'V024',
    plate_number: 'KA04MH5678',
    vehicle_type: 'Concrete Mixer',
    company: 'Apex Ready-Mix Concrete',
    driver_name: 'Sunil Rao',
    camera_id: 'Gate-01',
    entry_time: '09:35 AM',
    exit_time: null,
    duration_minutes: null,
    authorization_status: 'authorized',
    status: 'Currently Inside',
    date: '2026-09-17',
    ocr_confidence: 96,
  },
  {
    id: 'log-003',
    vehicle_id: 'V025',
    plate_number: 'MH12PQ9988',
    vehicle_type: 'Dump Truck',
    company: 'Titan Earthworks & Quarry',
    driver_name: 'Dinesh Mane',
    camera_id: 'Gate-02',
    entry_time: '09:50 AM',
    exit_time: null,
    duration_minutes: null,
    authorization_status: 'authorized',
    status: 'Currently Inside',
    date: '2026-09-17',
    ocr_confidence: 95,
  },
  {
    id: 'log-004',
    vehicle_id: 'V026',
    plate_number: 'TN40XX9999',
    vehicle_type: 'Lorry',
    company: 'Unknown / Unregistered',
    driver_name: 'Unknown',
    camera_id: 'Gate-01',
    entry_time: '11:24 AM',
    exit_time: '11:29 AM',
    duration_minutes: 5,
    authorization_status: 'unauthorized',
    status: 'Exited',
    date: '2026-09-17',
    ocr_confidence: 93,
  },
  {
    id: 'log-005',
    vehicle_id: 'V027',
    plate_number: 'KL07CE7711',
    vehicle_type: 'Pickup',
    company: 'Skyline Site Surveying',
    driver_name: 'George K',
    camera_id: 'Gate-03',
    entry_time: '08:15 AM',
    exit_time: '11:45 AM',
    duration_minutes: 210,
    authorization_status: 'authorized',
    status: 'Exited',
    date: '2026-09-17',
    ocr_confidence: 98,
  },
  {
    id: 'log-006',
    vehicle_id: 'V028',
    plate_number: 'KA51MD3344',
    vehicle_type: 'Van',
    company: 'ElectroSpark MEP Services',
    driver_name: 'Anand Kumar',
    camera_id: 'Gate-03',
    entry_time: '10:15 AM',
    exit_time: null,
    duration_minutes: null,
    authorization_status: 'expired',
    status: 'Currently Inside',
    date: '2026-09-17',
    ocr_confidence: 92,
  },
  {
    id: 'log-007',
    vehicle_id: 'V029',
    plate_number: 'DL01CA4321',
    vehicle_type: 'Flatbed',
    company: 'SteelCraft Infrastructure',
    driver_name: 'Jaswinder S',
    camera_id: 'Gate-02',
    entry_time: '07:30 AM',
    exit_time: '09:10 AM',
    duration_minutes: 100,
    authorization_status: 'authorized',
    status: 'Exited',
    date: '2026-09-17',
    ocr_confidence: 94,
  },
  {
    id: 'log-008',
    vehicle_id: 'V030',
    plate_number: 'TS09UB4567',
    vehicle_type: 'Truck',
    company: 'Precision Cranes & Rigging',
    driver_name: 'Venkatesh N',
    camera_id: 'Gate-01',
    entry_time: '08:45 AM',
    exit_time: '10:15 AM',
    duration_minutes: 90,
    authorization_status: 'authorized',
    status: 'Exited',
    date: '2026-09-17',
    ocr_confidence: 96,
  }
];

export const INITIAL_ANALYTICS: AnalyticsData = {
  total_vehicles_today: 127,
  unique_vehicles: 94,
  authorized_vehicles: 119,
  unauthorized_vehicles: 8,
  currently_inside: 32,
  average_stay_duration_minutes: 48,
  total_plate_detections: 1482,
  low_confidence_ocr_detections: 14,
  vehicles_per_hour: [
    { hour: '06:00', count: 4, authorized: 4, unauthorized: 0 },
    { hour: '07:00', count: 12, authorized: 11, unauthorized: 1 },
    { hour: '08:00', count: 24, authorized: 22, unauthorized: 2 },
    { hour: '09:00', count: 31, authorized: 29, unauthorized: 2 },
    { hour: '10:00', count: 26, authorized: 25, unauthorized: 1 },
    { hour: '11:00', count: 18, authorized: 17, unauthorized: 1 },
    { hour: '12:00', count: 12, authorized: 11, unauthorized: 1 },
  ],
  vehicle_type_distribution: [
    { type: 'Truck', count: 48, percentage: 38 },
    { type: 'Concrete Mixer', count: 32, percentage: 25 },
    { type: 'Dump Truck', count: 24, percentage: 19 },
    { type: 'Van', count: 12, percentage: 9 },
    { type: 'Pickup', count: 8, percentage: 6 },
    { type: 'Flatbed', count: 3, percentage: 3 },
  ],
  daily_traffic: [
    { date: '2026-09-11', day: 'Fri', count: 118, authorized: 112, unauthorized: 6 },
    { date: '2026-09-12', day: 'Sat', count: 96, authorized: 93, unauthorized: 3 },
    { date: '2026-09-13', day: 'Sun', count: 42, authorized: 41, unauthorized: 1 },
    { date: '2026-09-14', day: 'Mon', count: 135, authorized: 126, unauthorized: 9 },
    { date: '2026-09-15', day: 'Tue', count: 142, authorized: 134, unauthorized: 8 },
    { date: '2026-09-16', day: 'Wed', count: 131, authorized: 124, unauthorized: 7 },
    { date: '2026-09-17', day: 'Thu', count: 127, authorized: 119, unauthorized: 8 },
  ],
  average_stay_by_type: [
    { type: 'Concrete Mixer', duration_minutes: 38 },
    { type: 'Dump Truck', duration_minutes: 52 },
    { type: 'Truck', duration_minutes: 65 },
    { type: 'Flatbed', duration_minutes: 115 },
    { type: 'Van', duration_minutes: 85 },
    { type: 'Pickup', duration_minutes: 42 },
  ],
  frequently_seen_vehicles: [
    {
      plate_number: 'TN38AB1234',
      vehicle_type: 'Truck',
      company: 'ABC Construction Ltd',
      visit_count: 34,
      authorization_status: 'authorized',
      last_seen: '2026-09-17 10:47 AM',
    },
    {
      plate_number: 'KA04MH5678',
      vehicle_type: 'Concrete Mixer',
      company: 'Apex Ready-Mix Concrete',
      visit_count: 29,
      authorization_status: 'authorized',
      last_seen: '2026-09-17 09:35 AM',
    },
    {
      plate_number: 'MH12PQ9988',
      vehicle_type: 'Dump Truck',
      company: 'Titan Earthworks & Quarry',
      visit_count: 22,
      authorization_status: 'authorized',
      last_seen: '2026-09-17 09:50 AM',
    },
    {
      plate_number: 'TN22BZ8890',
      vehicle_type: 'Concrete Mixer',
      company: 'ABC Construction Ltd',
      visit_count: 19,
      authorization_status: 'authorized',
      last_seen: '2026-09-17 08:20 AM',
    },
    {
      plate_number: 'TN40XX9999',
      vehicle_type: 'Lorry',
      company: 'Unregistered Hauler',
      visit_count: 6,
      authorization_status: 'unauthorized',
      last_seen: '2026-09-17 11:24 AM',
    },
  ],
  ocr_performance: {
    successful_ocr: 1410,
    low_confidence_ocr: 58,
    unreadable_plates: 14,
    success_rate: 95.1,
  },
};

export const SAMPLE_MULTI_FRAME_FUSION_DEMO = {
  vehicle_id: 'V023',
  frame_count: 5,
  individual_frames: [
    {
      frame_number: 1,
      raw_text: 'TN38AB?234',
      confidence: 82,
      blur_score: 54,
      quality_status: 'Poor' as const,
      timestamp: '10:32:14.200',
    },
    {
      frame_number: 2,
      raw_text: 'TN38AB1234',
      confidence: 94,
      blur_score: 86,
      quality_status: 'Good' as const,
      timestamp: '10:32:14.400',
    },
    {
      frame_number: 3,
      raw_text: 'TN38AB1234',
      confidence: 96,
      blur_score: 89,
      quality_status: 'Good' as const,
      timestamp: '10:32:14.600',
    },
    {
      frame_number: 4,
      raw_text: 'TN38A?1234',
      confidence: 85,
      blur_score: 62,
      quality_status: 'Poor' as const,
      timestamp: '10:32:14.800',
    },
    {
      frame_number: 5,
      raw_text: 'TN38AB1234',
      confidence: 97,
      blur_score: 92,
      quality_status: 'Good' as const,
      timestamp: '10:32:15.000',
    },
  ],
  fused_plate: 'TN38AB1234',
  fused_confidence: 97,
  character_voting: [
    { position: 0, chosen_char: 'T', candidates: [{ char: 'T', votes: 5, avg_conf: 98 }] },
    { position: 1, chosen_char: 'N', candidates: [{ char: 'N', votes: 5, avg_conf: 97 }] },
    { position: 2, chosen_char: '3', candidates: [{ char: '3', votes: 5, avg_conf: 96 }] },
    { position: 3, chosen_char: '8', candidates: [{ char: '8', votes: 5, avg_conf: 97 }] },
    { position: 4, chosen_char: 'A', candidates: [{ char: 'A', votes: 5, avg_conf: 94 }] },
    { position: 5, chosen_char: 'B', candidates: [{ char: 'B', votes: 4, avg_conf: 96 }, { char: '?', votes: 1, avg_conf: 85 }] },
    { position: 6, chosen_char: '1', candidates: [{ char: '1', votes: 4, avg_conf: 95 }, { char: '?', votes: 1, avg_conf: 82 }] },
    { position: 7, chosen_char: '2', candidates: [{ char: '2', votes: 5, avg_conf: 97 }] },
    { position: 8, chosen_char: '3', candidates: [{ char: '3', votes: 5, avg_conf: 98 }] },
    { position: 9, chosen_char: '4', candidates: [{ char: '4', votes: 5, avg_conf: 98 }] },
  ],
  algorithm: 'Multi-Frame Weighted Character Fusion' as const,
};
